CREATE ROLE professores NOCREATEDB NOCREATEROLE INHERIT NOLOGIN NOBYPASSRLS CONNECTION LIMIT 10;

ALTER ROLE professores PASSWORD '';

CREATE ROLE moduletwo LOGIN PASSWORD '';

DROP ROLE moduletwo;

CREATE ROLE moduletwo LOGIN PASSWORD '' IN ROLE professores;